name: fogosmobile
description: Fogos.pt new iOS and Android app

version: 4.0.0+40000

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  sentry: 7.8.0
  cupertino_icons: ^1.0.5
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  redux_logging: ^0.5.1
  mapbox_gl: ^0.16.0
  http: ^1.1.0
  dio: ^5.3.0
  firebase_messaging: ^14.6.5
  firebase_analytics: ^10.4.4
  firebase_core: ^2.15.0
  shared_preferences: ^2.2.0
  diacritic: ^0.1.4
  url_launcher: ^6.1.12
  flutter_markdown: ^0.6.17
  auto_size_text: ^3.0.0

  font_awesome_flutter: 10.5.0

  share: ^2.0.4
  cached_network_image: ^3.2.3

  #ui
  flutter_svg: ^2.0.7
  charts_flutter: ^0.12.0
  modal_progress_hud_nsn: ^0.4.0

  #localizations
  intl: 0.18.1
  equatable: ^2.0.5
  logger: ^1.4.0
  # TODO(GP): Find another way of compiling translations
  # intl_translation: ^0.17.10

dependency_overrides:
  intl: 0.17.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/partners/